// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjibappxfzvjczbktwov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqaWJhcHB4Znp2amN6Ymt0d292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTQ3MjYsImV4cCI6MjA3MTA5MDcyNn0.xxFhAQeouBvhP35q-6bdIfGGHOWY0pCXP06-rGAje5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});